import logging
from datetime import date, datetime, timedelta
from typing import List, Dict, Tuple

import pytz

from src.config import LANGUAGE, TIMEZONE, DAYS_FR, DAYS_EN, MONTHS_FR
from src.fetchers.espn import SportEvent
from src.fetchers.cycling import CyclingEvent

logger = logging.getLogger("tele7sport")

TZ = pytz.timezone(TIMEZONE)


def _fmt_date_fr(d: date) -> str:
    return f"{DAYS_FR[d.weekday()]} {d.day} {MONTHS_FR[d.month]}"


def _fmt_date_en(d: date) -> str:
    return d.strftime("%A %B %d")


def _fmt_date(d: date) -> str:
    return _fmt_date_fr(d) if LANGUAGE == "fr" else _fmt_date_en(d)


def _fmt_time(dt_utc: datetime) -> str:
    local = dt_utc.astimezone(TZ)
    return local.strftime("%H:%M")


def _local_date(dt_utc: datetime) -> date:
    return dt_utc.astimezone(TZ).date()


def _channel_badge(channel: str) -> str:
    colors = {
        "canal+": "#1A1A1A", "canal+ sport": "#1A1A1A", "canal+ foot": "#1A1A1A",
        "canal+ premier league": "#1A1A1A",
        "bein sports": "#6B2EAF", "bein sports 1": "#6B2EAF",
        "bein sports 2": "#6B2EAF", "bein sports 3": "#6B2EAF", "bein sports max": "#6B2EAF",
        "eurosport": "#003F87", "eurosport 1": "#003F87", "eurosport 2": "#003F87",
        "tf1": "#E4002B", "france 2": "#1E5AA8", "france 3": "#005BBB",
        "france 4": "#6B2D7B", "france tv": "#1E5AA8",
        "m6": "#F7A600", "l'équipe": "#F5A623", "l'equipe": "#F5A623",
        "dazn": "#0C0C0C", "rmc sport": "#E10600",
        "red bull tv": "#DB0A40", "nba league pass": "#1D428A",
        "nfl game pass": "#013369", "prime video": "#00A8E1",
    }
    color = colors.get(channel.lower(), "#6b7280")
    return (
        f'<span style="display:inline-block;background:{color};color:white;'
        f'padding:2px 8px;border-radius:4px;font-size:10px;font-weight:600;'
        f'margin-left:4px;vertical-align:middle;letter-spacing:0.3px;">'
        f'{channel}</span>'
    )


def _sport_badge(emoji: str, label: str) -> str:
    return (
        f'<span style="display:inline-block;background:#f0f4ff;color:#333;'
        f'padding:4px 10px;border-radius:6px;font-size:13px;font-weight:700;'
        f'margin-bottom:6px;">{emoji} {label}</span>'
    )


def _score_display(ev: SportEvent) -> str:
    if ev.status == "completed" and ev.home_score is not None:
        return f"{ev.home_team} {ev.home_score} - {ev.away_score} {ev.away_team}"
    return ""


def _highlight_star() -> str:
    return (
        '<span style="display:inline-block;background:linear-gradient(135deg,#FFD700,#FFA500);'
        'color:#333;padding:1px 6px;border-radius:4px;font-size:10px;font-weight:800;'
        'margin-left:4px;vertical-align:middle;">⭐ À NE PAS RATER</span>'
    )


# ── Main render function ────────────────────────────────────

def render_newsletter(
    upcoming_events: List[SportEvent],
    past_events: List[SportEvent],
    cycling_upcoming: List[CyclingEvent],
    cycling_past: List[CyclingEvent],
    channels_map: Dict[str, List[str]],
    week_start: date,
    week_end: date,
    prev_week_start: date,
    prev_week_end: date,
) -> Tuple[str, str]:
    """
    Render the full HTML newsletter.
    Returns (html_body, subject_line).
    """
    if LANGUAGE == "fr":
        title = "AU MENU CETTE SEMAINE"
        week_label = f"Semaine du {week_start.day} au {week_end.day} {MONTHS_FR[week_end.month]} {week_end.year}"
        highlights_title = "🌟 GRANDES RENCONTRES À NE PAS RATER"
        schedule_title = "📅 PROGRAMME JOUR PAR JOUR"
        results_title = "📊 RÉSULTATS DE LA SEMAINE PASSÉE"
        no_events = "Aucun événement cette semaine pour vos favoris."
        no_results = "Aucun résultat la semaine passée."
        cycling_title = "🚴 ÉVÉNEMENTS CYCLISME"
        footer_text = "Généré automatiquement par Télé7Sport"
        subject = f"📺 Télé7Sport — {week_label}"
    else:
        title = "THIS WEEK'S MENU"
        week_label = f"Week of {week_start.strftime('%b %d')} — {week_end.strftime('%b %d, %Y')}"
        highlights_title = "🌟 MUST-WATCH EVENTS"
        schedule_title = "📅 DAY BY DAY SCHEDULE"
        results_title = "📊 LAST WEEK'S RESULTS"
        no_events = "No events this week for your favorites."
        no_results = "No results from last week."
        cycling_title = "🚴 CYCLING EVENTS"
        footer_text = "Automatically generated by Télé7Sport"
        subject = f"📺 Télé7Sport — {week_label}"

    # ── Group upcoming events by day ────────────────────────
    events_by_day: Dict[date, List[SportEvent]] = {}
    for ev in upcoming_events:
        d = _local_date(ev.datetime_utc)
        events_by_day.setdefault(d, []).append(ev)

    # ── Group past events by league ─────────────────────────
    results_by_league: Dict[str, List[SportEvent]] = {}
    for ev in past_events:
        if ev.status == "completed":
            results_by_league.setdefault(ev.league_label, []).append(ev)

    # ── Highlights ──────────────────────────────────────────
    highlight_events = [ev for ev in upcoming_events if ev.is_highlight]

    # ── Start building HTML ─────────────────────────────────
    html_parts = [_html_head(title, week_label)]

    # Highlights section
    if highlight_events:
        html_parts.append(_section_open(highlights_title))
        for ev in highlight_events:
            ch_key = f"{ev.league_id}:{ev.home_team}:{ev.away_team}"
            channels = channels_map.get(ch_key, [])
            html_parts.append(_render_highlight_event(ev, channels))
        html_parts.append(_section_close())

    # Day-by-day schedule
    html_parts.append(_section_open(schedule_title))
    if not events_by_day and not cycling_upcoming:
        html_parts.append(f'<p style="color:#888;font-style:italic;">{no_events}</p>')
    else:
        current = week_start
        while current <= week_end:
            day_events = events_by_day.get(current, [])
            day_cycling = [c for c in cycling_upcoming if c.start_date <= current <= c.end_date]
            if day_events or day_cycling:
                html_parts.append(_day_header(current))
                # Group day events by league
                by_league: Dict[str, List[SportEvent]] = {}
                for ev in day_events:
                    by_league.setdefault(f"{ev.emoji} {ev.league_label}", []).append(ev)
                for league_header, evs in by_league.items():
                    html_parts.append(_league_header(league_header, evs[0].round_info))
                    for ev in evs:
                        ch_key = f"{ev.league_id}:{ev.home_team}:{ev.away_team}"
                        channels = channels_map.get(ch_key, [])
                        html_parts.append(_render_schedule_event(ev, channels))
                # Cycling for this day — grouped by league
                cycling_by_league: Dict[str, List[CyclingEvent]] = {}
                for ce in day_cycling:
                    cycling_by_league.setdefault(f"{ce.emoji} {ce.league_label}", []).append(ce)
                for league_hdr, ces in cycling_by_league.items():
                    html_parts.append(_league_header(league_hdr, ""))
                    for ce in ces:
                        html_parts.append(_render_cycling_event(ce, current))
            current += timedelta(days=1)
    html_parts.append(_section_close())

    # Cycling standalone section (multi-day events)
    standalone_cycling = [c for c in cycling_upcoming if c.end_date > c.start_date]
    if standalone_cycling:
        html_parts.append(_section_open(cycling_title))
        for ce in standalone_cycling:
            html_parts.append(_render_cycling_multi_day(ce))
        html_parts.append(_section_close())

    # Past results
    if results_by_league or cycling_past:
        html_parts.append(_section_open(results_title))
        for league_label, evs in results_by_league.items():
            emoji = evs[0].emoji if evs else ""
            html_parts.append(_league_header(f"{emoji} {league_label}", ""))
            for ev in evs:
                html_parts.append(_render_result_event(ev))
        for ce in cycling_past:
            html_parts.append(_render_cycling_result(ce))
        html_parts.append(_section_close())
    elif not results_by_league:
        html_parts.append(_section_open(results_title))
        html_parts.append(f'<p style="color:#888;font-style:italic;">{no_results}</p>')
        html_parts.append(_section_close())

    html_parts.append(_html_footer(footer_text))
    return "\n".join(html_parts), subject


# ── HTML template fragments ─────────────────────────────────

def _html_head(title: str, week_label: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="{LANGUAGE}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
* {{ box-sizing: border-box; margin: 0; padding: 0; }}
body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    background: #0d0d0d;
    color: #e0e0e0;
    line-height: 1.6;
}}
.container {{
    max-width: 640px;
    margin: 20px auto;
    background: #111111;
    border-radius: 12px;
    overflow: hidden;
    box-shadow: 0 4px 24px rgba(0,0,0,0.6);
}}
.header {{
    background: #0d0d0d;
    color: #ffffff;
    padding: 32px 28px;
    text-align: center;
    border-bottom: 3px solid #e74c3c;
}}
.header h1 {{
    font-size: 22px;
    font-weight: 800;
    letter-spacing: 1.5px;
    margin-bottom: 6px;
    text-transform: uppercase;
    color: #ffffff;
}}
.header h1 .accent {{
    color: #e74c3c;
}}
.header .subtitle {{
    font-size: 13px;
    color: #888;
    font-weight: 400;
    letter-spacing: 0.3px;
}}
.content {{
    padding: 0;
    background: #111111;
}}
.section {{
    padding: 20px 24px;
    background: #111111;
}}
.section + .section {{
    border-top: 1px solid #222222;
}}
.section-title {{
    font-size: 12px;
    font-weight: 700;
    color: #e74c3c;
    text-transform: uppercase;
    letter-spacing: 1.2px;
    padding-bottom: 10px;
    margin-bottom: 14px;
    border-bottom: 1px solid #2a2a2a;
}}
.day-header {{
    font-size: 12px;
    font-weight: 700;
    color: #ffffff;
    text-transform: uppercase;
    letter-spacing: 1px;
    padding: 10px 0 6px 0;
    margin-top: 18px;
    border-bottom: 1px solid #222222;
}}
.day-header:first-child {{
    margin-top: 0;
}}
.league-header {{
    font-size: 12px;
    font-weight: 600;
    color: #666666;
    padding: 8px 0 4px 0;
}}
.league-round {{
    font-weight: 400;
    color: #444444;
    margin-left: 6px;
}}
.event-row {{
    display: flex;
    align-items: center;
    padding: 9px 12px;
    margin: 3px 0;
    background: #1a1a1a;
    border-radius: 6px;
    font-size: 13px;
    border-left: 3px solid #e74c3c;
}}
.event-time {{
    min-width: 48px;
    font-weight: 700;
    color: #e74c3c;
    font-size: 13px;
    font-variant-numeric: tabular-nums;
}}
.event-teams {{
    flex: 1;
    font-weight: 500;
    color: #e0e0e0;
}}
.event-channels {{
    text-align: right;
}}
.highlight-card {{
    background: #1e1500;
    border: 1px solid #463200;
    border-radius: 8px;
    padding: 12px 16px;
    margin: 6px 0;
}}
.highlight-card .hl-teams {{
    font-size: 14px;
    font-weight: 700;
    color: #ffffff;
}}
.highlight-card .hl-info {{
    font-size: 12px;
    color: #777;
    margin-top: 4px;
}}
.result-row {{
    padding: 6px 12px;
    margin: 2px 0;
    font-size: 13px;
    border-radius: 6px;
    background: #1a1a1a;
    color: #aaaaaa;
}}
.result-win {{
    color: #4ade80;
    background: #0a1f0f;
}}
.result-lose {{
    color: #f87171;
    background: #1f0a0a;
}}

.footer {{
    background: #0d0d0d;
    padding: 20px 24px;
    text-align: center;
    font-size: 11px;
    color: #444444;
    border-top: 1px solid #1e1e1e;
}}
.footer a {{ color: #e74c3c; text-decoration: none; }}
@media (max-width:600px) {{
    .container {{ margin: 0; border-radius: 0; }}
    .header {{ padding: 24px 16px; }}
    .header h1 {{ font-size: 18px; }}
    .section {{ padding: 16px; }}
    .event-row {{ flex-wrap: wrap; }}
    .event-channels {{ width: 100%; text-align: left; margin-top: 4px; }}
}}
</style>
</head>
<body style="background:#0d0d0d;">
<div class="container">
    <div class="header">
        <h1>📺 <span class="accent">Télé7</span>Sport</h1>
        <div class="subtitle">{week_label}</div>
    </div>
    <div class="content">
"""


def _html_footer(footer_text: str) -> str:
    return f"""
    </div>
    <div class="footer">
        <p>{footer_text}</p>
        <p style="margin-top:6px;">
            <a href="https://tele7sport.vercel.app">Modifier mes préférences</a> · <a href="https://github.com/justinmartin/tele7sport">GitHub</a>
        </p>
    </div>
</div>
</body>
</html>"""


def _section_open(title: str) -> str:
    return f'<div class="section"><div class="section-title">{title}</div>'


def _section_close() -> str:
    return '</div>'


def _day_header(d: date) -> str:
    return f'<div class="day-header">{_fmt_date(d)}</div>'


def _league_header(label: str, round_info: str) -> str:
    round_html = f'<span class="league-round">— {round_info}</span>' if round_info else ""
    return f'<div class="league-header">{label} {round_html}</div>'


def _render_schedule_event(ev: SportEvent, channels: List[str]) -> str:
    time_str = _fmt_time(ev.datetime_utc)
    teams = f"{ev.home_team}  vs  {ev.away_team}"
    ch_html = " ".join(_channel_badge(ch) for ch in channels) if channels else ""
    highlight = _highlight_star() if ev.is_highlight else ""
    return (
        f'<div class="event-row">'
        f'<span class="event-time">{time_str}</span>'
        f'<span class="event-teams">{teams}{highlight}</span>'
        f'<span class="event-channels">{ch_html}</span>'
        f'</div>'
    )


def _render_highlight_event(ev: SportEvent, channels: List[str]) -> str:
    time_str = _fmt_time(ev.datetime_utc)
    d = _local_date(ev.datetime_utc)
    date_str = _fmt_date(d)
    ch_html = " ".join(_channel_badge(ch) for ch in channels) if channels else ""
    round_html = f" — {ev.round_info}" if ev.round_info else ""
    return (
        f'<div class="highlight-card">'
        f'<div class="hl-teams">{ev.emoji} {ev.home_team}  vs  {ev.away_team}</div>'
        f'<div class="hl-info">{date_str}, {time_str}{round_html} {ch_html}</div>'
        f'</div>'
    )


def _render_result_event(ev: SportEvent) -> str:
    if ev.home_score is None:
        return ""
    score = f"{ev.home_team} {ev.home_score} - {ev.away_score} {ev.away_team}"
    matched = ev.matched_team.lower() if ev.matched_team else ""
    home_is_fav = matched and matched in ev.home_team.lower()
    away_is_fav = matched and matched in ev.away_team.lower()

    if home_is_fav:
        won = ev.home_score > ev.away_score
    elif away_is_fav:
        won = ev.away_score > ev.home_score
    else:
        won = None

    if won is True:
        css = "result-row result-win"
        icon = "✅"
    elif won is False:
        css = "result-row result-lose"
        icon = "❌"
    else:
        css = "result-row"
        icon = "•"

    return f'<div class="{css}">{icon} {score}</div>'


def _render_cycling_event(ce: CyclingEvent, current_day: date) -> str:
    ch_html = " ".join(_channel_badge(ch) for ch in ce.channels_fr)
    loc = f" — {ce.location}" if ce.location else ""
    label = f"{ce.name}{loc}"
    return (
        f'<div class="event-row">'
        f'<span class="event-time">—</span>'
        f'<span class="event-teams">{ce.emoji} {label}</span>'
        f'<span class="event-channels">{ch_html}</span>'
        f'</div>'
    )


def _render_cycling_multi_day(ce: CyclingEvent) -> str:
    ch_html = " ".join(_channel_badge(ch) for ch in ce.channels_fr)
    loc = f" — {ce.location}" if ce.location else ""
    dates = f"{_fmt_date(ce.start_date)} → {_fmt_date(ce.end_date)}"
    label = f"{ce.name}{loc}"
    return (
        f'<div class="event-row">'
        f'<span class="event-time">—</span>'
        f'<span class="event-teams">{ce.emoji} {label}'
        f'<br><span style="font-size:11px;color:#555;">{dates}</span></span>'
        f'<span class="event-channels">{ch_html}</span>'
        f'</div>'
    )


def _render_cycling_result(ce: CyclingEvent) -> str:
    loc = f" — {ce.location}" if ce.location else ""
    return (
        f'<div class="result-row">'
        f'{ce.emoji} {ce.name}{loc}'
        f'</div>'
    )
